#if defined(WAVESHARE_RP2040_ONE)
#define PICOFLY_PIN_GLI 15
#define PICOFLY_PIN_SDA 12
#define PICOFLY_PIN_SCL 13

#define PICOFLY_PIN_LED 16
#define PICOFLY_PIN_LED_PWR 31
#define PICOFLY_PIN_RGB_MODE 25
#elif defined(WAVESHARE_RP2040_ZERO)
#define PICOFLY_PIN_GLI 15
#define PICOFLY_PIN_SDA 12
#define PICOFLY_PIN_SCL 13

#define PICOFLY_PIN_LED 16
#define PICOFLY_PIN_LED_PWR 31
#define PICOFLY_PIN_RGB_MODE 25
#elif defined(ADAFRUIT_ITSYBITSY_RP2040)
#define PICOFLY_PIN_GLI 24
#define PICOFLY_PIN_SDA 18
#define PICOFLY_PIN_SCL 19

#define PICOFLY_PIN_LED 17
#define PICOFLY_PIN_LED_PWR 16
#elif defined(SEEED_XIAO_RP2040)
#define PICOFLY_PIN_GLI 6
#define PICOFLY_PIN_SDA 3
#define PICOFLY_PIN_SCL 4

#define PICOFLY_PIN_LED 12
#define PICOFLY_PIN_LED_PWR 11
#define PICOFLY_PIN_LED_RED 17
#define PICOFLY_PIN_LED_GRN 16
#define PICOFLY_PIN_LED_BLU 25
#elif defined(PICOFLY_HAL9000)
#define PICOFLY_PIN_GLI 0
#define PICOFLY_PIN_SDA 0
#define PICOFLY_PIN_SCL 0

#define PICOFLY_PIN_LED 0
#define PICOFLY_PIN_LED_PWR 0
#elif defined(RASPBERRYPI_PICO)
#error "Not supported"
// #define PICOFLY_PIN_GLI 21
// #define PICOFLY_PIN_SDA 19
// #define PICOFLY_PIN_SCL 20

// #define PICOFLY_PIN_LED 25
// #define PICOFLY_PIN_LED_PWR 31
#else 
#error "No RP2040 board specified"
#endif



#define PICOFLY_PIN_DAT 29
#define PICOFLY_PIN_CMD 28
#define PICOFLY_PIN_CLK 27
#define PICOFLY_PIN_RST 26

#define PICOFLY_PIN_TEMP_PICO 29