#ifndef _BOARDS_PICOFLY_ADAFRUIT_ITSYBITSY_RP2040_H
#define _BOARDS_PICOFLY_ADAFRUIT_ITSYBITSY_RP2040_H

#define PICOFLY_ADAFRUIT_ITSYBITSY_RP2040

#define PICOFLY_PIN_GLI 24
#define PICOFLY_PIN_SDA 18
#define PICOFLY_PIN_SCL 19

#define PICOFLY_PIN_LED 17
#define PICOFLY_PIN_LED_PWR 16

#endif