#ifndef _BOARDS_PICOFLY_HAL9000_H
#define _BOARDS_PICOFLY_HAL9000_H

#define PICOFLY_HAL9000

#define PICOFLY_PIN_GLI 0
#define PICOFLY_PIN_SDA 0
#define PICOFLY_PIN_SCL 0

#define PICOFLY_PIN_LED 0
#define PICOFLY_PIN_LED_PWR 0

#endif