#ifndef _BOARDS_PICOFLY_SEEED_XIAO_RP2040_H
#define _BOARDS_PICOFLY_SEEED_XIAO_RP2040_H

#define PICOFLY_SEEED_XIAO_RP2040

#define PICOFLY_PIN_GLI 6
#define PICOFLY_PIN_SDA 3
#define PICOFLY_PIN_SCL 4

#define PICOFLY_PIN_LED 12
#define PICOFLY_PIN_LED_PWR 11
#define PICOFLY_PIN_LED_RED 17
#define PICOFLY_PIN_LED_GRN 16
#define PICOFLY_PIN_LED_BLU 25

#endif