#ifndef _BOARDS_PICOFLY_WAVESHARE_RP2040_ONE_H
#define _BOARDS_PICOFLY_WAVESHARE_RP2040_ONE_H

#define PICOFLY_WAVESHARE_RP2040_ONE

#define PICOFLY_PIN_GLI 15
#define PICOFLY_PIN_SDA 12
#define PICOFLY_PIN_SCL 13

#define PICOFLY_PIN_LED 16
#define PICOFLY_PIN_LED_PWR 31
#define PICOFLY_PIN_RGB_MODE 25

#endif