name: Build BrokenFly binaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     boards:
    #     - waveshare_rp2040_one
    #     - waveshare_rp2040_zero
    #     - adafruit_itsybitsy_rp2040
    #     - seeed_xiao_rp2040
          
    steps:
      # - name: Install dependencies
      #   run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build-tools/Dockerfile
          load: true
          tags: brokenfly-build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build with Docker
        run: | 
          ./build.sh
      
      - name: Generate release tag
        id: tag
        run: |
          VERSION=$(cat VERSION)
          GIT_VERSION=$(git describe --tags --always --dirty)
          RELEASE_TAG=BrokenFly-${VERSION}-${GIT_VERSION}
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "release_tag=$RELEASE_TAG"
          
      - name: Createa a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            build/*
  